# -*- coding: utf-8 -*-
"""file_renamer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Se8IaFgW3YK8Qe9j0E_300-_Fq5yEOyL
"""

import os

def renamer():
    i = 0 # initiate/iterate over files or lists
    path = "/content/sample_data"
    for filename in os.listdir(path):
        names = f"pic {i}.jpg"
        src = path + filename
        dest = path + names
        
        os.rename(src,dest)
        i = i + 1
    
if __name__ == "__main__":
    renamer()