# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FWQfNwVLbxhGV1zhjlTUCEAJUwR8YtMb
"""

import random

user_action = input("Enter a choice (Rock, Paper, Scissor): ")
possible_actions = ["Rock", "Paper", "Scissor"]
computer_action = random.choice(possible_actions)
print(f"\nYou choose {user_action}, computer choose {computer_action}.\n")

if user_action == computer_action:
    print(f"Both players selected {user_action}. It's a tie!")
elif user_action == "Rock":
    if computer_action == "scissors":
        print("Rock smashes scissor! You win!")
    else:
        print("Paper covers rock! You lose.")
elif user_action == "Paper":
    if computer_action == "rock":
        print("Paper covers rock! You win!")
    else:
        print("Scissor cuts paper! You lose.")
elif user_action == "Scissor":
    if computer_action == "Paper":
        print("Scissor cuts paper! You win!")
    else:
        print("Rock smashes scissor! You lose.")